#!/bin/zsh
if which pyenv > /dev/null; then
  pyenv install 2.7.13
  pyenv install 3.6.2
  pyenv virtualenv 2.7.13 neovim2
  pyenv virtualenv 3.6.2 neovim3
  pyenv activate neovim2
  pip install neovim
  pip install jedi
  pyenv activate neovim3
  pip install neovim
  pip install jedi
else
  echo "no pyenv, defaulting to vanilla python"
  pip install neovim
  pip install jedi
  pip3 install neovim3
  pip3 install jedi
fi
